# base images
FROM ubuntu:latest

# RUN command
RUN echo Hello~ It's shell type command.
RUN ["echo","hello~ It's exec ytpe command."]
RUN ["/bin/bash","-c","echo 'Hello~ It's /bin/bash execution in shell type command.'"]
